# TCL File Generated by Component Editor 17.0
# Sun Nov 05 08:33:09 CET 2017
# DO NOT MODIFY


# 
# GammaTable "GammaCorrectionTable" v1.0
# Henry Leinen 2017.11.05.08:33:09
# Implements a gamma correction table
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module GammaTable
# 
set_module_property DESCRIPTION "Implements a gamma correction table"
set_module_property NAME GammaTable
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Custom Components"
set_module_property AUTHOR "Henry Leinen"
set_module_property DISPLAY_NAME GammaCorrectionTable
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
# set_module_property STRUCTURAL_COMPOSITION_CALLBACK structural_hierarchy
set_module_property ELABORATION_CALLBACK elab_callback

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH fileset_callback
set_fileset_property QUARTUS_SYNTH TOP_LEVEL GammaTable
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false


# 
# parameters
# 
add_parameter COLOR_BITS_IN INTEGER 8 ""
set_parameter_property COLOR_BITS_IN DEFAULT_VALUE 8
set_parameter_property COLOR_BITS_IN DISPLAY_NAME COLOR_BITS_IN
set_parameter_property COLOR_BITS_IN TYPE INTEGER
set_parameter_property COLOR_BITS_IN UNITS bits
set_parameter_property COLOR_BITS_IN ALLOWED_RANGES {2 4 5 6 7 8 9 10}
set_parameter_property COLOR_BITS_IN DESCRIPTION ""
set_parameter_property COLOR_BITS_IN AFFECTS_GENERATION true
set_parameter_property COLOR_BITS_IN HDL_PARAMETER true
add_parameter COLOR_BITS_OUT INTEGER 8 ""
set_parameter_property COLOR_BITS_OUT DEFAULT_VALUE 8
set_parameter_property COLOR_BITS_OUT DISPLAY_NAME COLOR_BITS_OUT
set_parameter_property COLOR_BITS_OUT TYPE INTEGER
set_parameter_property COLOR_BITS_OUT UNITS bits
set_parameter_property COLOR_BITS_OUT ALLOWED_RANGES {2 4 5 6 7 8 9 10 11 12 13 14 15 16}
set_parameter_property COLOR_BITS_OUT DESCRIPTION ""
set_parameter_property COLOR_BITS_OUT AFFECTS_GENERATION true
set_parameter_property COLOR_BITS_OUT HDL_PARAMETER true
add_parameter NUM_CLIENTS INTEGER 1 ""
set_parameter_property NUM_CLIENTS DEFAULT_VALUE 1
set_parameter_property NUM_CLIENTS DISPLAY_NAME NumberOfClients
set_parameter_property NUM_CLIENTS DESCRIPTION "Number of clients"
set_parameter_property NUM_CLIENTS AFFECTS_GENERATION true
set_parameter_property NUM_CLIENTS ALLOWED_RANGES {1 2 3 4}
set_parameter_property NUM_CLIENTS AFFECTS_ELABORATION true
set_parameter_property NUM_CLIENTS GROUP "Client Control"
set_parameter_property NUM_CLIENTS HDL_PARAMETER false


#
# TCL Callback procedure to include the right files
#
proc elab_callback {} {
    if {[get_parameter NUM_CLIENTS] > 3} {
        set_interface_property gamma_channel4 ENABLED true
        set_port_property rgb4_in TERMINATION false
        set_port_property rgb4_out TERMINATION false
    } else {
        set_interface_property gamma_channel4 ENABLED false
        set_port_property rgb4_in TERMINATION true
        set_port_property rgb4_in TERMINATION_VALUE 0
        set_port_property rgb4_out TERMINATION true
    }
    if {[get_parameter NUM_CLIENTS] > 2} {
        set_interface_property gamma_channel3 ENABLED true
        set_port_property rgb3_in TERMINATION false
        set_port_property rgb3_out TERMINATION false
    } else {
        set_interface_property gamma_channel3 ENABLED false
        set_port_property rgb3_in TERMINATION true
        set_port_property rgb3_in TERMINATION_VALUE 0
        set_port_property rgb3_out TERMINATION true
    }
    if {[get_parameter NUM_CLIENTS] > 1} {
        set_interface_property gamma_channel2 ENABLED true
        set_port_property rgb2_in TERMINATION false
        set_port_property rgb2_out TERMINATION false
    } else {
        set_interface_property gamma_channel2 ENABLED false
        set_port_property rgb2_in TERMINATION true
        set_port_property rgb2_in TERMINATION_VALUE 0
        set_port_property rgb2_out TERMINATION true
    }
}
proc fileset_callback { entityName } {

    if {[get_parameter NUM_CLIENTS] == 1} {
        add_fileset_file LedGammaTable1.v VERILOG PATH "../_Components/Avalon_LedPanel _Client_Server/LedGammaTable1.v" TOP_LEVEL_FILE
    } else {
        if {[get_parameter NUM_CLIENTS] == 2} {
            add_fileset_file LedGammaTable2.v VERILOG PATH "../_Components/Avalon_LedPanel _Client_Server/LedGammaTable2.v" TOP_LEVEL_FILE
        } else {
            if {[get_parameter NUM_CLIENTS] == 3} {
                add_fileset_file LedGammaTable3.v VERILOG PATH "../_Components/Avalon_LedPanel _Client_Server/LedGammaTable3.v" TOP_LEVEL_FILE
            } else {
                if {[get_parameter NUM_CLIENTS] == 4} {
                    add_fileset_file LedGammaTable4.v VERILOG PATH "../_Components/Avalon_LedPanel _Client_Server/LedGammaTable4.v" TOP_LEVEL_FILE
                }
            }
        }
    }
}


# 
# display items
# 


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitStates 0
set_interface_property avalon_slave readWaitTime 0
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avalon_slave_address address Input COLOR_BITS_IN
add_interface_port avalon_slave avalon_slave_read read Input 1
add_interface_port avalon_slave avalon_slave_readdata readdata Output COLOR_BITS_OUT
add_interface_port avalon_slave avalon_slave_write write Input 1
add_interface_port avalon_slave avalon_slave_writedata writedata Input COLOR_BITS_OUT
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point gamma_channel1
# 
add_interface gamma_channel1 conduit end
set_interface_property gamma_channel1 associatedClock clock
set_interface_property gamma_channel1 associatedReset ""
set_interface_property gamma_channel1 ENABLED true

add_interface_port gamma_channel1 rgb1_in rgb_in Input 3*COLOR_BITS_IN
add_interface_port gamma_channel1 rgb1_out rgb_out Output 3*COLOR_BITS_OUT

# 
# connection point gamma_channel2
# 
add_interface gamma_channel2 conduit end
set_interface_property gamma_channel2 associatedClock clock
set_interface_property gamma_channel2 associatedReset ""
set_interface_property gamma_channel2 ENABLED true

add_interface_port gamma_channel2 rgb2_in rgb_in Input 3*COLOR_BITS_IN
add_interface_port gamma_channel2 rgb2_out rgb_out Output 3*COLOR_BITS_OUT

# 
# connection point gamma_channel3
# 
add_interface gamma_channel3 conduit end
set_interface_property gamma_channel3 associatedClock clock
set_interface_property gamma_channel3 associatedReset ""
set_interface_property gamma_channel3 ENABLED true

add_interface_port gamma_channel3 rgb3_in rgb_in Input 3*COLOR_BITS_IN
add_interface_port gamma_channel3 rgb3_out rgb_out Output 3*COLOR_BITS_OUT

# 
# connection point gamma_channel4
# 
add_interface gamma_channel4 conduit end
set_interface_property gamma_channel4 associatedClock clock
set_interface_property gamma_channel4 associatedReset ""
set_interface_property gamma_channel4 ENABLED true

add_interface_port gamma_channel4 rgb4_in rgb_in Input 3*COLOR_BITS_IN
add_interface_port gamma_channel4 rgb4_out rgb_out Output 3*COLOR_BITS_OUT
