# TCL File Generated by Component Editor 17.0
# Sat Nov 04 20:21:03 CET 2017
# DO NOT MODIFY


# 
# LedPanelSlave "LedPanelSlave" v1.0
# Henry Leinen 2017.11.04.20:21:03
# Implements the LedPanel Slave which must be connected to an LedPanelMaster
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LedPanelSlave
# 
set_module_property DESCRIPTION "Implements the LedPanel Slave which must be connected to an LedPanelMaster"
set_module_property NAME LedPanelSlave
set_module_property VERSION 1.5
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Custom Components"
set_module_property AUTHOR "Henry Leinen"
set_module_property DISPLAY_NAME LedPanelSlave
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LedPanelClient_Avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file LedMemoryClient_Avalon.v VERILOG PATH "../_Components/Avalon_LedPanel _Client_Server/LedMemoryClient_Avalon.v" TOP_LEVEL_FILE
# add_fileset_file LedPanelClient.v VERILOG PATH "../_Components/Avalon_LedPanel _Client_Server/LedPanelClient.v"
# add_fileset_file LedPanelMemory.v VERILOG PATH "../_Components/Avalon_LedPanel _Client_Server/LedPanelMemory.v"


# 
# parameters
# 
add_parameter DISPLAY_ROWS_LINES INTEGER 4
set_parameter_property DISPLAY_ROWS_LINES DEFAULT_VALUE 4
set_parameter_property DISPLAY_ROWS_LINES DISPLAY_NAME DISPLAY_ROWS_LINES
set_parameter_property DISPLAY_ROWS_LINES TYPE INTEGER
set_parameter_property DISPLAY_ROWS_LINES UNITS Bits
set_parameter_property DISPLAY_ROWS_LINES ALLOWED_RANGES {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16}
set_parameter_property DISPLAY_ROWS_LINES HDL_PARAMETER true
add_parameter DISPLAY_COLS_LINES INTEGER 6
set_parameter_property DISPLAY_COLS_LINES DEFAULT_VALUE 6
set_parameter_property DISPLAY_COLS_LINES DISPLAY_NAME DISPLAY_COLS_LINES
set_parameter_property DISPLAY_COLS_LINES TYPE INTEGER
set_parameter_property DISPLAY_COLS_LINES UNITS Bits
set_parameter_property DISPLAY_COLS_LINES ALLOWED_RANGES {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16}
set_parameter_property DISPLAY_COLS_LINES HDL_PARAMETER true
add_parameter COLOR_BITS INTEGER 8
set_parameter_property COLOR_BITS DEFAULT_VALUE 8
set_parameter_property COLOR_BITS DISPLAY_NAME COLOR_BITS
set_parameter_property COLOR_BITS TYPE INTEGER
set_parameter_property COLOR_BITS UNITS Bits
set_parameter_property COLOR_BITS ALLOWED_RANGES {1 2 4 8}
set_parameter_property COLOR_BITS HDL_PARAMETER true

# 
# display items
# 


#
# Elaboration callback 
#

# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point s1_mem
# 
add_interface s1_mem avalon end
set_interface_property s1_mem addressUnits WORDS
set_interface_property s1_mem associatedClock clock
set_interface_property s1_mem associatedReset reset
set_interface_property s1_mem bitsPerSymbol 8
set_interface_property s1_mem burstOnBurstBoundariesOnly false
set_interface_property s1_mem burstcountUnits WORDS
set_interface_property s1_mem explicitAddressSpan 0
set_interface_property s1_mem holdTime 0
set_interface_property s1_mem linewrapBursts false
set_interface_property s1_mem maximumPendingReadTransactions 0
set_interface_property s1_mem maximumPendingWriteTransactions 0
set_interface_property s1_mem readLatency 0
set_interface_property s1_mem readWaitStates 0
set_interface_property s1_mem readWaitTime 0
set_interface_property s1_mem setupTime 0
set_interface_property s1_mem timingUnits Cycles
set_interface_property s1_mem writeWaitTime 1
set_interface_property s1_mem ENABLED true
set_interface_property s1_mem EXPORT_OF ""
set_interface_property s1_mem PORT_NAME_MAP ""
set_interface_property s1_mem CMSIS_SVD_VARIABLES ""
set_interface_property s1_mem SVD_ADDRESS_GROUP ""

add_interface_port s1_mem s1_address address Input "(DISPLAY_ROWS_LINES+DISPLAY_COLS_LINES) - (0) + 1"
add_interface_port s1_mem s1_write write Input 1
add_interface_port s1_mem s1_writedata writedata Input 32
set_interface_assignment s1_mem embeddedsw.configuration.isFlash 0
set_interface_assignment s1_mem embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1_mem embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1_mem embeddedsw.configuration.isPrintableDevice 0


# 
# connection point s2_gamma
# 
add_interface s2_gamma avalon end
set_interface_property s2_gamma addressUnits WORDS
set_interface_property s2_gamma associatedClock clock
set_interface_property s2_gamma associatedReset reset
set_interface_property s2_gamma bitsPerSymbol 8
set_interface_property s2_gamma burstOnBurstBoundariesOnly false
set_interface_property s2_gamma burstcountUnits WORDS
set_interface_property s2_gamma explicitAddressSpan 0
set_interface_property s2_gamma holdTime 0
set_interface_property s2_gamma linewrapBursts false
set_interface_property s2_gamma maximumPendingReadTransactions 0
set_interface_property s2_gamma maximumPendingWriteTransactions 0
set_interface_property s2_gamma readLatency 0
set_interface_property s2_gamma readWaitStates 0
set_interface_property s2_gamma readWaitTime 0
set_interface_property s2_gamma setupTime 0
set_interface_property s2_gamma timingUnits Cycles
set_interface_property s2_gamma writeWaitTime 0
set_interface_property s2_gamma ENABLED true
set_interface_property s2_gamma EXPORT_OF ""
set_interface_property s2_gamma PORT_NAME_MAP ""
set_interface_property s2_gamma CMSIS_SVD_VARIABLES ""
set_interface_property s2_gamma SVD_ADDRESS_GROUP ""

add_interface_port s2_gamma s2_address address Input "(COLOR_BITS)"
add_interface_port s2_gamma s2_write write Input 1
add_interface_port s2_gamma s2_writedata writedata Input 32
#add_interface_port s2_gamma s2_read read Input 1
#add_interface_port s2_gamma s2_readdata readdata Output 32
set_interface_assignment s2_gamma embeddedsw.configuration.isFlash 0
set_interface_assignment s2_gamma embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s2_gamma embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s2_gamma embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_led
# 
add_interface conduit_led conduit end
set_interface_property conduit_led associatedClock clock_ext
set_interface_property conduit_led associatedReset ""
set_interface_property conduit_led ENABLED true
set_interface_property conduit_led EXPORT_OF ""
set_interface_property conduit_led PORT_NAME_MAP ""
set_interface_property conduit_led CMSIS_SVD_VARIABLES ""
set_interface_property conduit_led SVD_ADDRESS_GROUP ""

add_interface_port conduit_led led_addr led_addr Output 4
add_interface_port conduit_led led_blank led_blank Output 1
add_interface_port conduit_led led_blue led_blue Output 2
add_interface_port conduit_led led_clock led_clock Output 1
add_interface_port conduit_led led_green led_green Output 2
add_interface_port conduit_led led_latch led_latch Output 1
add_interface_port conduit_led led_red led_red Output 2


# 
# connection point interconnect
# 
add_interface interconnect conduit end
set_interface_property interconnect associatedClock clock_ext
set_interface_property interconnect associatedReset reset
set_interface_property interconnect ENABLED true
set_interface_property interconnect EXPORT_OF ""
set_interface_property interconnect PORT_NAME_MAP ""
set_interface_property interconnect CMSIS_SVD_VARIABLES ""
set_interface_property interconnect SVD_ADDRESS_GROUP ""

add_interface_port interconnect memAddrMst memaddrmst Input DISPLAY_ROWS_LINES+DISPLAY_COLS_LINES
add_interface_port interconnect bitplaneMst bitplanemst Input 3
add_interface_port interconnect backbufferMst backbuffermst Input 1
add_interface_port interconnect ADDR_MST addr_mst Input 4
add_interface_port interconnect BLANK_MST blank_mst Input 1
add_interface_port interconnect CLK_LED_MST clk_led_mst Input 1
add_interface_port interconnect LATCH_MST latch_mst Input 1


# 
# connection point clock_ext
# 
add_interface clock_ext clock end
set_interface_property clock_ext clockRate 200000000
set_interface_property clock_ext ENABLED true
set_interface_property clock_ext EXPORT_OF ""
set_interface_property clock_ext PORT_NAME_MAP ""
set_interface_property clock_ext CMSIS_SVD_VARIABLES ""
set_interface_property clock_ext SVD_ADDRESS_GROUP ""

add_interface_port clock_ext ext_clock200 clk Input 1

