# TCL File Generated by Component Editor 17.0
# Sat Nov 04 20:23:25 CET 2017
# DO NOT MODIFY


# 
# LedPanelMaster "LedPanelMaster" v1.0
# Henry Leinen 2017.11.04.20:23:25
# Master Module for any number of LedPanel Slaves
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LedPanelMaster
# 
set_module_property DESCRIPTION "Master Module for any number of LedPanel Slaves"
set_module_property NAME LedPanelMaster
set_module_property VERSION 1.5
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Custom Components"
set_module_property AUTHOR "Henry Leinen"
set_module_property DISPLAY_NAME LedPanelMaster
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LedPanelServer_Avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file LedMemoryServer_Avalon.v VERILOG PATH "../_Components/Avalon_LedPanel _Client_Server/LedMemoryServer_Avalon.v" TOP_LEVEL_FILE
add_fileset_file LedPanelServer.v VERILOG PATH "../_Components/Avalon_LedPanel _Client_Server/LedPanelServer.v"


# 
# parameters
# 
add_parameter DISPLAY_ROWS_LINES INTEGER 4 ""
set_parameter_property DISPLAY_ROWS_LINES DEFAULT_VALUE 4
set_parameter_property DISPLAY_ROWS_LINES DISPLAY_NAME DISPLAY_ROWS_LINES
set_parameter_property DISPLAY_ROWS_LINES WIDTH ""
set_parameter_property DISPLAY_ROWS_LINES TYPE INTEGER
set_parameter_property DISPLAY_ROWS_LINES UNITS Bits
set_parameter_property DISPLAY_ROWS_LINES ALLOWED_RANGES {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16}
set_parameter_property DISPLAY_ROWS_LINES DESCRIPTION ""
set_parameter_property DISPLAY_ROWS_LINES HDL_PARAMETER true
add_parameter DISPLAY_COLS_LINES INTEGER 6
set_parameter_property DISPLAY_COLS_LINES DEFAULT_VALUE 6
set_parameter_property DISPLAY_COLS_LINES DISPLAY_NAME DISPLAY_COLS_LINES
set_parameter_property DISPLAY_COLS_LINES TYPE INTEGER
set_parameter_property DISPLAY_COLS_LINES UNITS Bits
set_parameter_property DISPLAY_COLS_LINES ALLOWED_RANGES {1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16}
set_parameter_property DISPLAY_COLS_LINES HDL_PARAMETER true
add_parameter COLOR_BITS INTEGER 8
set_parameter_property COLOR_BITS DEFAULT_VALUE 8
set_parameter_property COLOR_BITS DISPLAY_NAME COLOR_BITS
set_parameter_property COLOR_BITS TYPE INTEGER
set_parameter_property COLOR_BITS UNITS Bits
set_parameter_property COLOR_BITS ALLOWED_RANGES {2 4 8}
set_parameter_property COLOR_BITS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point clock_ext
# 
add_interface clock_ext clock end
set_interface_property clock_ext clockRate 200000000
set_interface_property clock_ext ENABLED true
set_interface_property clock_ext EXPORT_OF ""
set_interface_property clock_ext PORT_NAME_MAP ""
set_interface_property clock_ext CMSIS_SVD_VARIABLES ""
set_interface_property clock_ext SVD_ADDRESS_GROUP ""

add_interface_port clock_ext ext_clock200 clk Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1


# 
# connection point interconnect
# 
add_interface interconnect conduit end
set_interface_property interconnect associatedClock clock_ext
set_interface_property interconnect associatedReset ""
set_interface_property interconnect ENABLED true
set_interface_property interconnect EXPORT_OF ""
set_interface_property interconnect PORT_NAME_MAP ""
set_interface_property interconnect CMSIS_SVD_VARIABLES ""
set_interface_property interconnect SVD_ADDRESS_GROUP ""

add_interface_port interconnect ADDR_MST addr_mst_out Output 4
add_interface_port interconnect BLANK_MST blank_mst Output 1
add_interface_port interconnect CLK_LED_MST clk_led_mst Output 1
add_interface_port interconnect LATCH_MST latch_mst Output 1
add_interface_port interconnect backbufferMst backbuffermst Output 1
add_interface_port interconnect bitplaneMst bitplanemst Output 3
add_interface_port interconnect memAddrMst memaddrmst Output DISPLAY_COLS_LINES+DISPLAY_ROWS_LINES


# 
# connection point s0_ctrl
# 
add_interface s0_ctrl avalon end
set_interface_property s0_ctrl addressUnits WORDS
set_interface_property s0_ctrl associatedClock clock
set_interface_property s0_ctrl associatedReset reset
set_interface_property s0_ctrl bitsPerSymbol 8
set_interface_property s0_ctrl burstOnBurstBoundariesOnly false
set_interface_property s0_ctrl burstcountUnits WORDS
set_interface_property s0_ctrl explicitAddressSpan 0
set_interface_property s0_ctrl holdTime 0
set_interface_property s0_ctrl linewrapBursts false
set_interface_property s0_ctrl maximumPendingReadTransactions 0
set_interface_property s0_ctrl maximumPendingWriteTransactions 0
set_interface_property s0_ctrl readLatency 0
set_interface_property s0_ctrl readWaitTime 1
set_interface_property s0_ctrl setupTime 0
set_interface_property s0_ctrl timingUnits Cycles
set_interface_property s0_ctrl writeWaitTime 0
set_interface_property s0_ctrl ENABLED true
set_interface_property s0_ctrl EXPORT_OF ""
set_interface_property s0_ctrl PORT_NAME_MAP ""
set_interface_property s0_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property s0_ctrl SVD_ADDRESS_GROUP ""

add_interface_port s0_ctrl s0_address address Input 2
add_interface_port s0_ctrl s0_write write Input 1
add_interface_port s0_ctrl s0_writedata writedata Input 32
add_interface_port s0_ctrl s0_read read Input 1
add_interface_port s0_ctrl s0_readdata readdata Output 32
set_interface_assignment s0_ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment s0_ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0_ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0_ctrl embeddedsw.configuration.isPrintableDevice 0

