# TCL File Generated by Component Editor 17.0
# Fri Nov 03 08:14:16 CET 2017
# DO NOT MODIFY


# 
# LedPanel "LedPanel" v1.5
# Henry Leinen 2017.11.03.08:14:16
# This component allows access to an LED Panel.
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LedPanel
# 
set_module_property DESCRIPTION "This component allows access to an LED Panel."
set_module_property NAME LedPanel
set_module_property VERSION 1.5
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Custom Components"
set_module_property AUTHOR "Henry Leinen"
set_module_property DISPLAY_NAME LedPanel
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LedPanel_Avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file LedPanel.v VERILOG PATH ../_Components/Avalon_LedPanel/LedPanel.v
add_fileset_file LedPanelMemory.v VERILOG PATH ../_Components/Avalon_LedPanel/LedPanelMemory.v
add_fileset_file LedMemory_Avalon.v VERILOG PATH ../_Components/Avalon_LedPanel/LedMemory_Avalon.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DISPLAY_ROWS_LINES INTEGER 4
set_parameter_property DISPLAY_ROWS_LINES DEFAULT_VALUE 4
set_parameter_property DISPLAY_ROWS_LINES DISPLAY_NAME DISPLAY_ROWS_LINES
set_parameter_property DISPLAY_ROWS_LINES TYPE INTEGER
set_parameter_property DISPLAY_ROWS_LINES UNITS None
set_parameter_property DISPLAY_ROWS_LINES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DISPLAY_ROWS_LINES HDL_PARAMETER true
add_parameter DISPLAY_COLS_LINES INTEGER 6
set_parameter_property DISPLAY_COLS_LINES DEFAULT_VALUE 6
set_parameter_property DISPLAY_COLS_LINES DISPLAY_NAME DISPLAY_COLS_LINES
set_parameter_property DISPLAY_COLS_LINES TYPE INTEGER
set_parameter_property DISPLAY_COLS_LINES UNITS None
set_parameter_property DISPLAY_COLS_LINES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DISPLAY_COLS_LINES HDL_PARAMETER true
add_parameter COLOR_BITS INTEGER 8 ""
set_parameter_property COLOR_BITS DEFAULT_VALUE 8
set_parameter_property COLOR_BITS DISPLAY_NAME COLOR_BITS
set_parameter_property COLOR_BITS WIDTH ""
set_parameter_property COLOR_BITS TYPE INTEGER
set_parameter_property COLOR_BITS ENABLED false
set_parameter_property COLOR_BITS UNITS None
set_parameter_property COLOR_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property COLOR_BITS DESCRIPTION ""
set_parameter_property COLOR_BITS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock200 clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock external_clock
set_interface_property conduit associatedReset ""
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit led_green green Output 2
add_interface_port conduit led_blue blue Output 2
add_interface_port conduit led_addr addr Output 4
add_interface_port conduit led_clock clock Output 1
add_interface_port conduit led_blank blank Output 1
add_interface_port conduit led_latch latch Output 1
add_interface_port conduit led_red red Output 2


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint display_ctrl
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1


# 
# connection point display_mem
# 
add_interface display_mem avalon end
set_interface_property display_mem addressUnits WORDS
set_interface_property display_mem associatedClock clock
set_interface_property display_mem associatedReset reset
set_interface_property display_mem bitsPerSymbol 8
set_interface_property display_mem burstOnBurstBoundariesOnly false
set_interface_property display_mem burstcountUnits WORDS
set_interface_property display_mem explicitAddressSpan 0
set_interface_property display_mem holdTime 0
set_interface_property display_mem linewrapBursts false
set_interface_property display_mem maximumPendingReadTransactions 0
set_interface_property display_mem maximumPendingWriteTransactions 0
set_interface_property display_mem readLatency 0
set_interface_property display_mem readWaitTime 1
set_interface_property display_mem setupTime 0
set_interface_property display_mem timingUnits Cycles
set_interface_property display_mem writeWaitTime 0
set_interface_property display_mem ENABLED true
set_interface_property display_mem EXPORT_OF ""
set_interface_property display_mem PORT_NAME_MAP ""
set_interface_property display_mem CMSIS_SVD_VARIABLES ""
set_interface_property display_mem SVD_ADDRESS_GROUP ""

add_interface_port display_mem s1_address address Input "(DISPLAY_ROWS_LINES+DISPLAY_COLS_LINES) - (0) + 1"
add_interface_port display_mem s1_write write Input 1
add_interface_port display_mem s1_writedata writedata Input 32
set_interface_assignment display_mem embeddedsw.configuration.isFlash 0
set_interface_assignment display_mem embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment display_mem embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment display_mem embeddedsw.configuration.isPrintableDevice 0


# 
# connection point external_clock
# 
add_interface external_clock clock end
set_interface_property external_clock clockRate 200000000
set_interface_property external_clock ENABLED true
set_interface_property external_clock EXPORT_OF ""
set_interface_property external_clock PORT_NAME_MAP ""
set_interface_property external_clock CMSIS_SVD_VARIABLES ""
set_interface_property external_clock SVD_ADDRESS_GROUP ""

add_interface_port external_clock debug_clock clk Input 1


# 
# connection point display_ctrl
# 
add_interface display_ctrl avalon end
set_interface_property display_ctrl addressUnits WORDS
set_interface_property display_ctrl associatedClock clock
set_interface_property display_ctrl associatedReset reset
set_interface_property display_ctrl bitsPerSymbol 8
set_interface_property display_ctrl burstOnBurstBoundariesOnly false
set_interface_property display_ctrl burstcountUnits WORDS
set_interface_property display_ctrl explicitAddressSpan 0
set_interface_property display_ctrl holdTime 0
set_interface_property display_ctrl linewrapBursts false
set_interface_property display_ctrl maximumPendingReadTransactions 0
set_interface_property display_ctrl maximumPendingWriteTransactions 0
set_interface_property display_ctrl readLatency 0
set_interface_property display_ctrl readWaitStates 0
set_interface_property display_ctrl readWaitTime 0
set_interface_property display_ctrl setupTime 0
set_interface_property display_ctrl timingUnits Cycles
set_interface_property display_ctrl writeWaitTime 0
set_interface_property display_ctrl ENABLED true
set_interface_property display_ctrl EXPORT_OF ""
set_interface_property display_ctrl PORT_NAME_MAP ""
set_interface_property display_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property display_ctrl SVD_ADDRESS_GROUP ""

add_interface_port display_ctrl s0_address address Input 1
add_interface_port display_ctrl s0_write write Input 1
add_interface_port display_ctrl s0_writedata writedata Input 32
add_interface_port display_ctrl s0_read read Input 1
add_interface_port display_ctrl s0_readdata readdata Output 32
set_interface_assignment display_ctrl embeddedsw.configuration.isFlash 0
set_interface_assignment display_ctrl embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment display_ctrl embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment display_ctrl embeddedsw.configuration.isPrintableDevice 0

