# TCL File Generated by Component Editor 17.1
# Sun Nov 12 12:19:22 CET 2017
# DO NOT MODIFY


# 
# PwmOuput "PwmOutput" v1.0
# Henry Leinen 2017.11.12.12:19:22
# Allows the generate PWM outputs
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module PwmOuput
# 
set_module_property DESCRIPTION "Allows the generate PWM outputs"
set_module_property NAME PwmOuput
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Custom Components"
set_module_property AUTHOR "Henry Leinen"
set_module_property DISPLAY_NAME PwmOutput
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL PwmOut_Avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file PwmOut_Avalon.v VERILOG PATH ../_Components/Avalon_PwmOut/PwmOut_Avalon.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter NUMBER_OUTPUTS INTEGER 1 ""
set_parameter_property NUMBER_OUTPUTS DEFAULT_VALUE 1
set_parameter_property NUMBER_OUTPUTS DISPLAY_NAME NUMBER_OUTPUTS
set_parameter_property NUMBER_OUTPUTS TYPE INTEGER
set_parameter_property NUMBER_OUTPUTS UNITS None
set_parameter_property NUMBER_OUTPUTS ALLOWED_RANGES 1:16
set_parameter_property NUMBER_OUTPUTS DESCRIPTION ""
set_parameter_property NUMBER_OUTPUTS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point s0_command
# 
add_interface s0_command avalon end
set_interface_property s0_command addressUnits WORDS
set_interface_property s0_command associatedClock clock
set_interface_property s0_command associatedReset reset
set_interface_property s0_command bitsPerSymbol 8
set_interface_property s0_command burstOnBurstBoundariesOnly false
set_interface_property s0_command burstcountUnits WORDS
set_interface_property s0_command explicitAddressSpan 0
set_interface_property s0_command holdTime 0
set_interface_property s0_command linewrapBursts false
set_interface_property s0_command maximumPendingReadTransactions 0
set_interface_property s0_command maximumPendingWriteTransactions 0
set_interface_property s0_command readLatency 0
set_interface_property s0_command readWaitStates 0
set_interface_property s0_command readWaitTime 0
set_interface_property s0_command setupTime 0
set_interface_property s0_command timingUnits Cycles
set_interface_property s0_command writeWaitTime 0
set_interface_property s0_command ENABLED true
set_interface_property s0_command EXPORT_OF ""
set_interface_property s0_command PORT_NAME_MAP ""
set_interface_property s0_command CMSIS_SVD_VARIABLES ""
set_interface_property s0_command SVD_ADDRESS_GROUP ""

add_interface_port s0_command s0_command_address address Input "NUMBER_OUTPUTS+1"
add_interface_port s0_command s0_command_read read Input 1
add_interface_port s0_command s0_command_readdata readdata Output 32
add_interface_port s0_command s0_command_write write Input 1
add_interface_port s0_command s0_command_writedata writedata Input 32
set_interface_assignment s0_command embeddedsw.configuration.isFlash 0
set_interface_assignment s0_command embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0_command embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0_command embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pwm_out
# 
add_interface pwm_out conduit end
set_interface_property pwm_out associatedClock clock
set_interface_property pwm_out associatedReset ""
set_interface_property pwm_out ENABLED true
set_interface_property pwm_out EXPORT_OF ""
set_interface_property pwm_out PORT_NAME_MAP ""
set_interface_property pwm_out CMSIS_SVD_VARIABLES ""
set_interface_property pwm_out SVD_ADDRESS_GROUP ""

add_interface_port pwm_out pwm pwm_out Output "NUMBER_OUTPUTS"

